version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        environment:
          TERM: xterm-256color
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: ./test
